library(shiny)
library(shinythemes)
library(robumeta)
library(DT)
library(knitr)
library(tidyverse)
library(kableExtra)
library(plotly)
library(rclipboard)
library(metafor)
library(clubSandwich)

source("ui.R")
source("server.R")
source("extra/example.R")
source("tidy_meta.R")
options(knitr.kable.NA = '')

shinyApp(ui = ui, server = server)

